---

- name: Enable additional yum repos
  copy: src=additional_centos_repos.repo
      dest=/etc/yum.repos.d/additional_centos_repos.repo


#
#   Mount /data directory onto persistent EBS storage for any instance data that
#   needs to outlive the instance  ********* moved to external_data_volume role
#
#- name: Format zombie WP data volume
#  filesystem: fstype=ext4 dev={{data_vol_dev_name}}
#
#- name: create data dir for mount point
#  file: path=/data state=directory
#
#- name: Mount EBS device as docker data
#  mount: name=/data src={{data_vol_dev_name}} fstype=ext4 state=mounted


#- name: Enable EPEL repo
#  yum: "name='{{ item }}' state=present disable_gpg_check=true"
#  with_items:
#    - http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm

#
#   Install Docker
#

- name: Install Docker
  yum: "name='{{ item }}' state=present disable_gpg_check=true"
  with_items:
#    - http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
    - docker-io

- name: Install Python
  yum: "name='{{ item }}' state=present disable_gpg_check=true"
  with_items:
    - python-pip
    - python-docker-py

- name: Install GIT
  yum: "name='{{ item }}' state=present disable_gpg_check=true"
  with_items:
    - git

- name: Docker-PY
  pip: name=docker-py version=1.1.0

- name: start Docker
  service: name=docker state=started enabled=yes

- name: Remove sudo tty requirement which breaks rsync module
  lineinfile: regexp="^Defaults\s+requiretty" dest=/etc/sudoers state=absent