- hosts: all
  sudo: yes

  tasks:

    - name: get mysql conatiner ip
      sudo: yes
      shell: docker ps | grep zombie-web | awk '{ print $1 }'
      register: zombie_container

    - name: get mysql root password
      shell: docker exec {{zombie_container.stdout}} tail -n 1 /mysql-root-pw.txt
      register: root_pass

    - debug: var=zombie_container

    - name: copy snapshot to sever
      copy: src=../snapshots/zombie_mysqldump_all.sql dest=.

    - name: mysqldump
      shell: docker exec {{zombie_container.stdout}} mysql --user=root --password={{root_pass.stdout}} < zombie_mysqldump_all.sql
      sudo: true

#    - name: Delete snapshot on server
#      file: path=zombie_mysqldump_all.sql state=absent

