- hosts: all
  gather_facts: false
  sudo: yes

  tasks:

    - name: get mysql conatiner ip
      shell: docker ps | grep zombie-web | awk '{ print $1 }'
      register: zombie_container

    - name: get mysql root password
      shell: docker exec {{zombie_container.stdout}} tail -n 1 /mysql-root-pw.txt
      register: root_pass

    - name: get mysql root password
      shell: docker exec {{zombie_container.stdout}} tail -n 1 /wordpress-db-pw.txt
      register: wordpress_pass

    - debug: var=wordpress_pass


#
#   Upload and import all of the Mysql data
#

    - name: copy snapshot to sever
      copy: src=../snapshots/zombie_mysqldump_all_latest.sql dest=.

    - name: mysql import
      shell: docker exec -i {{zombie_container.stdout}} mysql --user=root --password={{root_pass.stdout}} < zombie_mysqldump_all_latest.sql
      sudo: true

#    - name: Delete snapshot on server
#      file: path=zombie_mysqldump_all.sql state=absent



#
#   Copy Wordpress files (plugins, config, etc)
#

    - file:  path=/var/sync_wp state=directory mode=0755

    - name: copy WP config to server
      synchronize: src=../snapshots/www dest=/var/sync_wp rsync_path="sudo rsync"

    - name: update wordpress db password
      lineinfile: dest="/var/sync_wp/www/wp-config.php" regexp="DB_PASSWORD" line="define('DB_PASSWORD', '{{wordpress_pass.stdout}}');"

    - name: Run volume copy container
      shell: docker run --rm -v /var/sync_wp:/var/sync_wp --volumes-from zombie-web-volumes flashashen/zombie-web cp -r /var/sync_wp/www /usr/share/nginx

#    - name: copy db snapshot to server
#      copy: src=../snapshots/zombie_mysqldump_all_latest.sql dest=/tmp/zombie_mysqldump_all_latest.sql
#
##    - name: import snapshot
##      mysql_db: state=import login_user=root login_password={{root_pass.stdout}} name=all target=/tmp/zombie_mysqldump_all_latest.sql
#
#    - name: import snapshot
#      shell: mysql -u root -p{{root_pass.stdout}} < /tmp/zombie_mysqldump_all_latest.sql
