--- # Create ec2 instance playbook

- hosts: all
  gather_facts: false
#  remote_user: "{{initial_remote_user}}"
#  vars:
#       ansible_ssh_pass: tcuser
#       ansible_ssh_user: docker
##       private_key_file: "{{initial_remote_key}}"

  tasks:


    - name: create user
      user: name={{local_user}}

    - name: install python selinux module
      yum: name=libselinux-python


    - name: setup authorized key
      authorized_key: user={{local_user}} key=https://github.com/flashashen.keys
#      authorized_key: user={{username}} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: add sudo privilege
      lineinfile: dest=/etc/sudoers state=present regexp='^%{{username}} ALL\=' line='%{{username}} ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'