--- # Site confgiration for all hosts

# map instance tags to roles

- hosts: zombie-web
  gather_facts: true
  sudo: yes


  roles:
#   - rhel_docker
   - zombie_wp_db_restore
   - { role: zombie_wp_init }
#   - { role: zombie_wp_init, host_wp_www_dir: "/workspace/zombiewww" }
   - zombie_wp_web_restore
   - zombie_wp_set_hostname
#   - zombie_nlp_server




