--- # Site confgiration for all hosts

# map instance tags to roles

- hosts: all
  gather_facts: false
  sudo: yes


  roles:
          - rhel_docker
#          - zombie

  vars:

      # aws is setting the device name when assoicated w the instance. The ec_vol attachemnt isnt
      # allowing device name to be specified so we'll have to rely on default. aws names start at sdf
      # and run though sdp. On the centos image the OS changes this to xvdf - xvdp.
      #vol_dev_name: "/dev/sdf"
      data_vol_dev_name: "/dev/xvdf"

