- hosts: zombie
  gather_facts: true
  sudo: yes


  roles:
   - zombie_wp_db_backup

  - name: Create DB container
     sudo: yes
     docker:
       image: mysql/mysql-server
       name: zombie-db
      # pull: always
       state: started
       restart_policy: always
       ports:
           - "3306"
  #     volumes_from: zombie-db-volume
       env:
         MYSQL_ROOT_PASSWORD: "{{db_root_pass}}"
