# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|


    # hostmanager plugin to update hosts files automatically so boxes can find each other. If you
    # don't have the plugin installed issue this command:
    #
    #       > vagrant plugin install vagrant-hostmanager
    #
    config.hostmanager.enabled = true


    config.vm.box = "hansode/centos-6.7-x86_64"


   #config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
 #    vb.gui = true

    # Customize the amount of memory on the VM:
    #vb.memory = "5120"
  #end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL


 config.ssh.insert_key = false


  config.vm.define "zombie_wp" do |zombie_wp|
        zombie_wp.vm.hostname = "zombie"
        zombie_wp.vm.network "private_network",
            ip: "192.168.33.100",
            guest: 22,
            host: 2200,
            id: "ssh",
            auto_correct: true
        zombie_wp.vm.synced_folder "~/workspace", "/workspace"
        zombie_wp.hostmanager.enabled = true
        zombie_wp.hostmanager.aliases = %w(zombie_wp zombiepoetryproject.com www.zombiepoetryproject.com)
        zombie_wp.vm.provision "ansible" do |ansible|
            ansible.limit = 'all'
            #ansible.raw_arguments  = "--ask-vault-pass"
            #ansible.playbook = "backup.yml"
            #ansible.playbook = "restore.yml"
            ansible.playbook = "host_zombie_wp.yml"
            ansible.verbose = "vvvv"
            ansible.groups = {
                "zombie_wp"  =>  ["zombie_wp"],
                "vagrant"  =>  ["zombie_wp"],
            }
        end
    end



end