
dsh: 2
ns: flash.zombie


vars:
  REPO_WEB: flashashen/zombie-web
  TAG_WEB: "20181010"
  JAVA_HOME: /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/
  INFECT_BUILD_DIR: zombie-infect/build/static
  INFECT_WWW_DIR: www/wp-content/plugins/zombie-posts/resources/infect
  stack_name: zombie
  OPT_COMPOSE_OVERRIDE: ""

  CMD_BUILD_INFECT: &CMD_BUILD_INFECT
    - cd zombie-infect && npm run build
    - cp {{INFECT_BUILD_DIR}}/js/main*.js {{INFECT_WWW_DIR}}/js/infectbundle.js
    - cp {{INFECT_BUILD_DIR}}/js/main*js.map {{INFECT_WWW_DIR}}/css/infectbundle.js.map
    - cp {{INFECT_BUILD_DIR}}/css/main*.css {{INFECT_WWW_DIR}}/css/infectbundle.css


up: docker stack deploy --with-registry-auth -c {{COMPOSE_FILENAME}} {{stack_name}}
stop: docker stack remove {{stack_name}}
ps: "{{CMD_PS}}"


contexts:

  prod:
    vars:
      service: web
      DOCKER_HOST: mini:2375
      repo: "{{REPO_WEB}}"
      tag: "{{TAG_WEB}}"
    up:
      - "{{CMD_DOCKER_PUSH}}"
      - docker pull {{DOCKER_IMAGE}}
      - docker stack deploy --with-registry-auth -c {{COMPOSE_FILENAME}} {{stack_name}}
      - docker service update --force --image {{DOCKER_IMAGE}} {{stack_name}}_web
    stop: docker stack remove {{stack_name}}
    ps: "{{CMD_PS}}"
    logs: "{{CMD_LOGS}}"

  nlp:
    vars:
      service: nlp
      _DSH_CTX_WORK_DIR: zombie-nlp
      repo: "flashashen/zombie-nlp"
      tag: latest

    build:
      - mvn install
    logs: "{{CMD_LOGS}}"


  web:
    vars:
      service: web
      _DSH_CTX_WORK_DIR: zombie-web
      repo: "{{REPO_WEB}}"
      tag: "{{TAG_WEB}}"

    logs: "{{CMD_LOGS}}"
    build:
      - *CMD_BUILD_INFECT
      - export DOCKER_HOST={{DOCKER_HOST_LOCAL}} && docker build -t {{DOCKER_IMAGE}} .
    release: export DOCKER_HOST={{DOCKER_HOST_LOCAL}} && docker push {{DOCKER_IMAGE}}
    update: docker service update --force --image {{DOCKER_IMAGE}} {{stack_name}}_{{service}}


infectdebug:
  - cd zombie-infect; npm start &
#  - cd server; npm run server &
#  - open -a Google\ Chrome --args --disable-web-security --user-data-dir

infectchrome:
  - pkill -a -i "Google Chrome"
  - open -a Google\ Chrome --args --disable-web-security --user-data-dir

infectbuild: *CMD_BUILD_INFECT




wpsyncn_to_mini: rsync -azP ./zombie-web/www/ flash@zombie-server:/Applications/MAMP/htdocs/

edit_secrets: ansible-vault edit provision/group_vars/zombie-web
edit_inv: vim provision/main.inventory

#setup_user: 'ansible -vvv --extra-vars "username=$(whoami)" {{ansible_ssh_options}}  provision/setup_user.yml --limit $1'
setup_user: ansible-playbook provision/setup_user.yml  --ask-pass -vvvv --limit

provision: ansible-playbook provision/site_wp.yml --limit
nlp: ansible-playbook provision/site_nlp.yml --limit

wp_backup: ansible-playbook provision/wp_backup.yml --limit
wp_restore: ansible-playbook provision/wp_restore.yml --limit
wp_reset_hostname: ansible-playbook provision/wp_sethostname.yml --limit

db_backup: ansible-playbook provision/db_backup.yml --limit
db_restore: ansible-playbook provision/db_restore.yml --limit

wp_user_list: ansible-playbook provision/user_list.yml --limit

