
version: '3.3'


volumes:
  db:
  uploads:


services:

  proxy:
    image: traefik:1.6.5
    ports:
     - target: 80
       published: 80
       protocol: tcp
       mode: host
     - target: 443
       published: 443
       protocol: tcp
       mode: host
     - target: 8080
       published: 9004
       protocol: tcp
       mode: host
    volumes:
     - type: bind
       source: /var/run/docker.sock
       target: /var/run/docker.sock
       # target: /tmp/docker.sock
    command: --web --docker --docker.swarmmode --debug


  db:
    image: mysql:5.7.23
    volumes:
      - db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${ZOMBIE_DB_ROOT_PASS}"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: "${WORDPRESS_DB_USER}"
      MYSQL_PASSWORD: "${WORDPRESS_DB_PASSWORD}"

  adminer:
    image: adminer
    ports:
      - 8081:8080

  nlp:
    image: flashashen/zombie-nlp:1.0-SNAPSHOT
    ports:
      - "8080:8080"

  web:
    image: "${REPO_WEB}:${TAG_WEB}"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:www.zombiepoetryproject.com"
        - "traefik.backend=web"
        - "traefik.port=80"
    volumes:
      - uploads:/var/www/html/wp-content/uploads
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: www.zombiepoetryproject.com
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
#      WORDPRESS_DB_USER: "root"
#      WORDPRESS_DB_PASSWORD: "${ZOMBIE_DB_ROOT_PASS}"





