


version: '3.3'


volumes:
  db:
  uploads:


services:

  proxy:
    image: traefik:1.6.5
    ports:
     - target: 80
       published: 80
       protocol: tcp
       mode: host
     - target: 443
       published: 443
       protocol: tcp
       mode: host
     - target: 8080
       published: 9004
       protocol: tcp
       mode: host
    volumes:
     - type: bind
       source: /var/run/docker.sock
       target: /var/run/docker.sock
       # target: /tmp/docker.sock
    command: --web --docker --docker.swarmmode --debug


  db:
#    image: mysql:5.7.23
    image: ${DOCKER_IMAGE_DB}
    volumes:
      - db:/var/lib/mysql
#    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${ZOMBIE_DB_ROOT_PASS}"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: "${WORDPRESS_DB_USER}"
      MYSQL_PASSWORD: "${WORDPRESS_DB_PASSWORD}"

  adminer:
    image: adminer
    ports:
      - 8081:8080

#  nlp:
#    image: "${DOCKER_IMAGE_NLP}"
#    ports:
#      - "8080:8080"

  web:
    image: "${DOCKER_IMAGE_WEB}"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:www.zombiepoetryproject.local"
        - "traefik.backend=web"
        - "traefik.port=80"
#    volumes:
#      - uploads:/var/www/html/wp-content/uploads
#      - ./zombie-web/www/wp-content/plugins:/var/www/html/wp-content/plugins
#      - ./zombie-web/www/wp-content/themes:/var/www/html/wp-content/themes
    extra_hosts:
      - "www.zombiepoetryproject.nlp.com:192.168.1.12"
      - "www.zombiepoetryproject.local:127.0.0.1"
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: www.zombiepoetryproject.com
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
#      WORDPRESS_DB_USER: "root"
#      WORDPRESS_DB_PASSWORD: "${ZOMBIE_DB_ROOT_PASS}"





