#
## !! nginx proxy doesn't work with compose V 2 b/c container ip resolution fails. There is a note on
version: '2'

services:

  zombie-db-volume:
    image: mysql/mysql-server
    name: zombie-db-volume
    state: present
    volumes:
        - /var/lib/mysql
    env:
      MYSQL_ROOT_PASSWORD: "{{db_root_pass}}"


   db:
      image: mysql/mysql-server
      name: zombie-db
      state: started
      restart_policy: always
      ports:
          - "3306"
      volumes_from: zombie-db-volume
      env:
        MYSQL_ROOT_PASSWORD: "{{db_root_pass}}"

  zombie-nlp:
      image: flashashen/zombie-nlp
      state: started
      restart_policy: always
      ports:
        - "8080:8080"


  zombie-web-volumes:
     build: zombie-web
     image: flashashen/zombie-web-nodb:20170102
     state: present

     volumes:
       - zombie-web/wwww:/var/www/html

  zombie-web:
     build: zombie-web
     image: flashashen/zombie-web-nodb:20170102
     # pull: always
    ports:
     - "80:80"
    #  - "3306:3306"
    volumes_from:
     - zombie-web-volumes
    links:
#     - zombie-nlp
     - db:mysql







