---

#
#   Run docker container with Zombie nlp server
#


#- name: template docker-compose
#  template: src="docker-compose.yml" dest="." #owner=root group=root mode=0644


#- name: run docker-compose
#  command: docker-compose up -d


- name: install Docker base apps image
  sudo: yes
  docker:
    image: flashashen/zombie-nlp
    name: zombie-nlp
    pull: always
    state: started
    restart_policy: always
    ports:
        - "8080:8080"

