---

#
#   Run docker container with Zombie nlp server
#


#- name: template docker-compose
#  template: src="docker-compose.yml" dest="." #owner=root group=root mode=0644


#- name: run docker-compose
#  command: docker-compose up -d
#- name: Log into DockerHub
#  docker_login:
#    username: flashashen
#    password: duck3riz3!
#    email: flashashen@gmail.com

- name: login to docker repo
  shell: '{{docker_cmd}} login -p {{docker_pass}} -u flashashen'

- name: run zombie nlp app in docker
  sudo: yes
  docker:
    image: flashashen/zombie-nlp
    name: zombie-nlp
    pull: always
    state: started
    restart_policy: always
    ports:
        - "8080:8080"

