FROM arm32v7/wordpress

#COPY www /var/www/html
COPY www/wp-content/themes /var/www/html/wp-content/themes
COPY www/wp-content/plugins /var/www/html/wp-content/plugins
#COPY www/wp-content/uploads /var/www/html/wp-content/uploads
#COPY www/wp-content/