---



#
#   Upload and import all of the Mysql data
#


  - name: get filename of latest snapshot
    local_action: shell find $(pwd)/.. -name zombie_mysqldump_all*.sql | tail -n 1
    sudo: false
    changed_when: False
    register: last_db_dump

  - debug:
      var: last_db_dump


  - name: get base filename of latest snapshot
    local_action: shell basename `find .. -name zombie_mysqldump_all*.sql` | tail -n 1
    sudo: false
    changed_when: False
    register: last_db_dump_basename


  - name: copy snapshot to sever
    copy: src={{last_db_dump.stdout}} dest=.

#  - name: Restore database
#    mysql_db:
#      name: wordpress
#      state: import
#      target: "{{last_db_dump_basename.stdout}}"


  - name: mysql import
    shell: '/Applications/MAMP/Library/bin/mysql --user=root --password=root < {{last_db_dump_basename.stdout}}'
#    sudo: true

  - name: Delete snapshot on server
    file: path={{last_db_dump.stdout}} state=absent

