---

  - name: get mysql conatiner ip
    shell: docker ps | grep zombie-web | awk '{ print $1 }'
    register: zombie_container

  - name: get mysql root password
    shell: docker exec {{zombie_container.stdout}} tail -n 1 /mysql-root-pw.txt
    register: root_pass


#
#   Upload and import all of the Mysql data
#

  - name: get filename of latest snapshot
    local_action: shell basename `ls -Art ../snapshots/*.sql| tail -n 1`
    sudo: false
    register: last_db_dump

  - name: copy snapshot to sever
    copy: src=../snapshots/{{last_db_dump.stdout}} dest=.

  - name: mysql import
    shell: docker exec -i {{zombie_container.stdout}} mysql --user=root --password={{root_pass.stdout}} < {{last_db_dump.stdout}}
    sudo: true

  - name: Delete snapshot on server
    file: path={{last_db_dump.stdout}} state=absent

