---


  - name: Create volume container for db
    sudo: yes
    docker:
      image: mysql/mysql-server
      name: zombie-db-volume
      #pull: always
      state: present
      volumes:
          - /var/lib/mysql
      env:
        MYSQL_ROOT_PASSWORD: "{{db_root_pass}}"

  - name: Create DB container
    sudo: yes
    docker:
      image: mysql/mysql-server
      name: zombie-db
     # pull: always
      state: started
      restart_policy: always
      ports:
          - "3306"
 #     volumes_from: zombie-db-volume
      env:
        MYSQL_ROOT_PASSWORD: "{{db_root_pass}}"

  # wait for db to come up. import further down was failing
  # - name: wait for mysql to come up
  #   wait_for: port=3306


  - name: get mysql conatiner ip
    shell: "docker ps | grep zombie-db | awk '{ print $1 }'"
    changed_when: False
    register: db_container



#
#   Upload and import all of the Mysql data
#

  - name: get filename of latest snapshot
    local_action: shell basename `ls -Art ../snapshots/*.sql| tail -n 1`
    sudo: false
    changed_when: False
    register: last_db_dump

  - name: copy snapshot to sever
    copy: src=../snapshots/{{last_db_dump.stdout}} dest=.

  - name: mysql import
    shell: docker exec -i {{db_container.stdout}} mysql --user=root --password={{db_root_pass}} < {{last_db_dump.stdout}}
    sudo: true

  - name: Delete snapshot on server
    file: path={{last_db_dump.stdout}} state=absent

