---




    #wait for db to come up. import further down was failing
#  - name: wait for mysql to come up
#    wait_for: port=3306

  - name: get mysql conatiner ip
    shell: "{{docker_cmd}} ps | grep zombie_db | awk '{ print $1 }'"
    changed_when: False
    register: db_container


  - name: Wait for database to be available
    command: "{{docker_cmd}} exec {{db_container.stdout}} sh -c 'mysql -h mysql -uroot -p{{db_root_pass}} || true'"
    register: result
    until: result.rc == 0
    retries: 10
    delay: 3


#
#   Upload and import all of the Mysql data
#


  - name: get filename of latest snapshot
    local_action: shell find $(pwd)/.. -name zombie_mysqldump_all*.sql | tail -n 1
    sudo: false
    changed_when: False
    register: last_db_dump

  - debug:
      var: last_db_dump


  - name: get base filename of latest snapshot
    local_action: shell basename `find .. -name zombie_mysqldump_all*.sql` | tail -n 1
    sudo: false
    changed_when: False
    register: last_db_dump_basename

  - name: copy snapshot to sever
    copy: src={{last_db_dump.stdout}} dest=.

  - name: mysql import
    shell: '{{docker_cmd}} exec -i {{db_container.stdout}} mysql --user=root --password={{db_root_pass}} < {{last_db_dump_basename.stdout}}'
#    sudo: true

  - name: Delete snapshot on server
    file: path={{last_db_dump.stdout}} state=absent

