---

  - name: get mysql conatiner ip
    shell: docker ps | grep zombie-web | awk '{ print $1 }'
    register: zombie_container

  - name: get mysql root password
    shell: docker exec {{zombie_container.stdout}} tail -n 1 /mysql-root-pw.txt
    register: root_pass

  - name: get mysql root password
    shell: docker exec {{zombie_container.stdout}} tail -n 1 /wordpress-db-pw.txt
    register: wordpress_pass

  - debug: var=wordpress_pass



#
#   Copy Wordpress files (plugins, config, etc)
#

  - file:  path=/var/sync_wp state=directory mode=0755

  - name: copy WP config to server
    synchronize: src=../snapshots/nginx dest=/var/sync_wp rsync_path="sudo rsync"

  - name: update wordpress db password
    lineinfile: dest="/var/sync_wp/nginx/www/wp-config.php" regexp="DB_PASSWORD" line="define('DB_PASSWORD', '{{wordpress_pass.stdout}}');"

  - name: Run volume copy container
    shell: docker run --rm -v /var/sync_wp:/var/sync_wp --volumes-from zombie-web-volumes flashashen/zombie-web cp -r /var/sync_wp/nginx /usr/share/

