---

  - name: get mysql conatiner ip
    shell: "docker ps | grep zombie-web | awk '{ print $1 }'"
    register: zombie_container



#
#   Copy Wordpress files (plugins, config, etc)
#

  - file:  path=/var/sync_wp state=directory mode=0755

  - name: copy WP config to server
    synchronize: src=../snapshots/nginx dest=/var/sync_wp rsync_path="sudo rsync"

  - name: update wordpress db yser
    lineinfile: dest="/var/sync_wp/nginx/www/wp-config.php" regexp="DB_USER" line="define('DB_USER', '{{db_wordpress_user}}');"

  - name: update wordpress db password
    lineinfile: dest="/var/sync_wp/nginx/www/wp-config.php" regexp="DB_PASSWORD" line="define('DB_PASSWORD', '{{db_wordpress_password}}');"

  - name: update wordpress db host
    lineinfile: dest="/var/sync_wp/nginx/www/wp-config.php" regexp="DB_HOST" line="define('DB_HOST', 'mysql');"

  - name: Run volume copy container
    shell: docker run --rm -v /var/sync_wp:/var/sync_wp --volumes-from zombie-web-volumes flashashen/zombie-web cp -r /var/sync_wp/nginx/www/* {{wp_webroot}}

  - name: set owner and group of wp-content to www-data so plugins and themes can intalled from admin screen.
    shell: docker exec {{zombie_container.stdout}} chown -R www-data:www-data {{wp_webroot}}/wp-content
    
