---
- name: Load minion definition into masters
  command: /usr/bin/kubectl create -f /tmp/node-{{ item }}.json
  register: command_result
  failed_when: "'already exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "command_result.rc == 0"
  with_items:
        groups['minions']

- name: Delete minion definitions from masters
  file: path=/tmp/node-{{ item }}.json state=absent
  changed_when: false
  with_items:
        groups['minions']