---
#- name: Install etcd from Fedora
#  yum: pkg=etcd state=latest
  # etcd restart handler may not be needed
  #notify:
  #        - restart etcd

- name: install Kubernetes master packagees
  yum: pkg=kubernetes state=present  disable_gpg_check=yes

- name: Enable apiserver
  service: name=kube-apiserver enabled=yes state=started

- name: Enable controller-manager
  service: name=kube-controller-manager enabled=yes state=started

- name: Enable scheduler
  service: name=kube-scheduler enabled=yes state=started

- include: load_nodes.yml
  when: kube_node_via_api and not is_aws
  tags: load_nodes
