---

  - name: Create volume container for db
    sudo: yes
    docker:
      image: mysql/mysql-server
      name: zombie-db-volume
      #pull: always
      state: present
      volumes:
          - /var/lib/mysql
      env:
        MYSQL_ROOT_PASSWORD: "{{db_root_pass}}"
        MYSQL_DATABASE: wordpress
        MYSQL_USER: "{{db_wordpress_user}}"
        MYSQL_PASSWORD: "{{db_wordpress_password}}"


  - name: Create DB container
    sudo: yes
    docker:
      image: mysql/mysql-server
      name: "{{zombie_db_container_name}}"
     # pull: always
      state: started
      restart_policy: always
      ports:
          - "3306"
      volumes_from: zombie-db-volume
      env:
        MYSQL_ROOT_PASSWORD: "{{db_root_pass}}"
        MYSQL_DATABASE: wordpress
        MYSQL_USER: "{{db_wordpress_user}}"
        MYSQL_PASSWORD: "{{db_wordpress_password}}"
